apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    orgId: 1
    type: postgres
    access: proxy
    url: db:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: "disable"
      postgresVersion: 1500
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: true
    editable: true
